services:
  pogu:
    build: .
    image: ghcr.io/nawocci/pogu:latest
    container_name: pogu
    ports:
      - '127.0.0.1:8099:8099'
    volumes:
      - pogu-data:/data
    restart: unless-stopped

volumes:
  pogu-data:
